name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # or your preferred version

      # Step 3: Install front-end dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 4: Install back-end dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Step 5: Run front-end tests (using Mocha)
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      # Step 6: Run back-end tests (using Mocha)
      - name: Run backend tests
        run: |
          cd backend
          npm test

      # Step 7: Build front-end for production
      - name: Build frontend
        run: |
          cd frontend
          npm run build

    
